### ISSUE TITLE
Deprecated info on Ubuntu 22.04 LTS (it's working fine)

### ISSUE THREAD

**Issue by extremecarver** [agrenott/phyghtmap#1]
Thanks a lot for fixing the matplotlib issue - just as an info here the install on building/installing phyghtmap from source (current master version):

running install
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(

....... cut as it's not needed / working ----

Installed /usr/local/lib/python3.10/dist-packages/phyghtmap-2.23-py3.10.egg
Processing dependencies for phyghtmap==2.23
Searching for numpy>=1.24.2
Reading https://pypi.org/simple/numpy/
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Downloading https://files.pythonhosted.org/packages/c5/21/275cfa7731ee2e121b1bf85ddb21b8712fe2f409f02a8b61521af6e4993d/numpy-1.24.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=a51725a815a6188c662fb66fb32077709a9ca38053f0274640293a14fdd22978
Best match: numpy 1.24.2
Processing numpy-1.24.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Installing numpy-1.24.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl to /usr/local/lib/python3.10/dist-packages
Adding numpy 1.24.2 to easy-install.pth file
Installing f2py script to /usr/local/bin
Installing f2py3 script to /usr/local/bin
Installing f2py3.10 script to /usr/local/bin

Installed /usr/local/lib/python3.10/dist-packages/numpy-1.24.2-py3.10-linux-x86_64.egg
Searching for contourpy>=1.0.7
Reading https://pypi.org/simple/contourpy/
Downloading https://files.pythonhosted.org/packages/ec/59/5eac40e348a7bf803cea221bcd27f74a49cb81667b400fdfbb680e86e7bb/contourpy-1.0.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=87f4d8941a9564cda3f7fa6a6cd9b32ec575830780677932abdec7bcb61717b0
Best match: contourpy 1.0.7
Processing contourpy-1.0.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Installing contourpy-1.0.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl to /usr/local/lib/python3.10/dist-packages
Adding contourpy 1.0.7 to easy-install.pth file

Installed /usr/local/lib/python3.10/dist-packages/contourpy-1.0.7-py3.10-linux-x86_64.egg
Searching for bs4>=0.0.1
Reading https://pypi.org/simple/bs4/
Downloading https://files.pythonhosted.org/packages/10/ed/7e8b97591f6f456174139ec089c769f89a94a1a4025fe967691de971f314/bs4-0.0.1.tar.gz#sha256=36ecea1fd7cc5c0c6e4a1ff075df26d50da647b75376626cc186e2212886dd3a
Best match: bs4 0.0.1
Processing bs4-0.0.1.tar.gz
Writing /tmp/easy_install-z83e9uaq/bs4-0.0.1/setup.cfg
Running bs4-0.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-z83e9uaq/bs4-0.0.1/egg-dist-tmp-yo2_otlo
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

zip_safe flag not set; analyzing archive contents...
Moving bs4-0.0.1-py3.10.egg to /usr/local/lib/python3.10/dist-packages
Adding bs4 0.0.1 to easy-install.pth file

Installed /usr/local/lib/python3.10/dist-packages/bs4-0.0.1-py3.10.egg
Searching for matplotlib==3.5.1
Best match: matplotlib 3.5.1
Adding matplotlib 3.5.1 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for GDAL==3.4.1
Best match: GDAL 3.4.1
Adding GDAL 3.4.1 to easy-install.pth file

**Comment by agrenott** [comment]
I think the warning is telling you to install using `pip install .` instead of `./setup.py`.
Another solution seems to be to upgrade setuptools itself: https://stackoverflow.com/questions/73257839/setup-py-install-is-deprecated-warning-shows-up-every-time-i-open-a-terminal-i

**Comment by extremecarver** [comment]
Ah I tried this before your patch and forgot about it.
So for Ubuntu 22.04 it should be added to instructions that in addition you need to install PIP???
sudo apt-get install pip
pip install setuptools

(I don't think the older 58.0.2 version is needed - it was just the most up to date at the time of that comment).
I would not understand how to use pip install instead of the build file - I think in that case we would need some instructions for pip too - but I really don't know how pip works. Can only remember using it once a long time ago.

**Comment by agrenott** [comment]
I guess the proper way of installing it on Ubuntu inside a virtualenv (as I find it cleaner) would be something like:
`sudo apt update
sudo apt install python3 python3-pip python3-venv
# Install GDAL via system package, as it's painful to install through PIP
sudo apt install python3-gdal 
# Create virtual env
python3 -m venv my_venv
# Switch to venv
. ./my_venv/bin/activate
# Install phyghtmap with dependencies from latest git version
pip install git+https://github.com/agrenott/phyghtmap.git
`
