### ISSUE TITLE
Request for Improvement - B-Spline  instead of linear interpolation.

### ISSUE THREAD

**Issue by extremecarver** [agrenott/phyghtmap#2]
I've asked for this already on Panarchos discussion page - not sure how difficult it would be. But in very mountaineous/steep areas this would be the biggest possible improvment for phyghtmap.

OSM pbf data for contourlines created with gnuplot and b-spline interpolation looks much cleaner and in Garmin format also consumes less size. 

The contourlines map of kleineisel.de for example have this. The difference is really big when zoomed in very close in mountaineous areas. 

--simplifyContoursEpsilon=? helps a bit too - but is super slow and hence really impossible to use say on a Europe polygon - even on a very fast server with loads of RAM.

Not sure if gnuplot would be faster too. 
https://wiki.openstreetmap.org/wiki/Srtm2osm_perl is not working anymore - but that script was editable to also use b-spline interpolation with gnuplot and it required ASC data as input... I'm not sure if there is another way instead of gnuplot to use b-spline interpolation instead of linear interpolation with phyghtmap.

**Comment by agrenott** [comment]
Interesting idea.

Some details (English available in the second part of the post) about how kleineisel.de does it: http://www.kleineisel.de/blogs/index.php/osmmap/2022/06/21/hohenlinien-lidar-deutschland

Not sure how this could get smaller OSM files though, as it seems OSM doesn't support BSpline anyway. Maybe a better distribution of points in the cornering sections of contours?

**Comment by extremecarver** [comment]
Yes correct. The size saving in ism data is very small or non existent, however as the interpolation leads to a bit cleaner lines you could slightly increase the smoothing of resulting lines when working with the output leading to bigger savings in the map output. For Garmin maps with mkgmap I would expect about 5% smaller size at slightly better visual quality for Alps area. The advantage is less the less steep the area. It's basically a big difference for anywhere steeper than 50° with 20m interval lines, or 40° with 10m interval lines.

**Comment by extremecarver** [comment]
Oh yeah the screenshot I'm sure is also with different smoothing/simplification. The "old" version must have had much bigger simplification value. Still even without any simplification without b-spline interpolation cannot get a similarly well looking result. I'm pretty sure it's also more correct (e.g. on small creveases or ridges)

**Comment by agrenott** [comment]
Some leads worth digging into: 
- https://stackoverflow.com/a/37743178
- https://matplotlib.org/stable/api/path_api.html#matplotlib.path.Path.cleaned

Need to assess the impact on performances. However if we can clean the path by removing some nodes, additional computing cost might be compensated by gain on the Output.writenodes (which is the highest time consumer).

**Comment by agrenott** [comment]
I've added an experimental option adding smoothing of generated contours via splines. I'm not convinced of the results though. It looks overall nicer, but introduces a lot of artifacts.

For example, original contours:
![image](https://user-images.githubusercontent.com/12431371/225314572-fc41a1be-74ad-4a31-87a3-fbe85a5bfe7c.png)

Smoothed ones:
![image](https://user-images.githubusercontent.com/12431371/225314656-fd9dd2c7-1ed6-4eba-a594-2b477ff5aeff.png)

I might give a try by super sampling the original HGT file instead (which I hope would avoid the artifacts, but wonder how much it will impact the performances).

**Comment by extremecarver** [comment]
What was your source data, SRTM or Lidar? But yeah the artifacts and even line cross overs in some cases look pretty bad. With those lines crossing it looks like the result is fitted onto a grid or low resolution raster (like for example a garmin map that has 5.4m resolution only)
I'm thinking maybe it only makes sense for high quality source data like LIDAR and for sure no hgt with voids?

**Comment by agrenott** [comment]
Source of this sample was "view1", so taken from ﻿﻿http://www.viewfinderpanoramas.org/Coverage%20map%20viewfinderpanoramas_org1.htm. Seems depending on the area it can come from various sources.

The lines crossing come from the fact I transform resulting paths to splines independently, so there's no relationship between them. Some loops are even created for some single path when creating the spline.

**Comment by extremecarver** [comment]
Oh yeah. Actually it would be nice to have a folder that allows custom hgt files without messing with the download option. Right now if you want to download your own hgt files and place them in a folder like view1 you then need to mess with the viewfinderhgtindex_1.txt file. Including the info about tiles you downloaded so they are recognized. I don't care too much about this but it would be more user friendly to have a custom folder that is just read in manually and added to an index/or not requiring the index file at all. 

My first preference is always the hgt files from sonny (sonn.4lima.de) which I then place together into view1 folder and adapt the index file to include them

**Comment by agrenott** [comment]
Input data interpolation provides better results (introducing small artifacts on seawater boundaries, but doesn't seem so bad.

![image](https://user-images.githubusercontent.com/12431371/226328853-b2790df8-c108-4c13-aeeb-76036ce06535.png)

Raw (blue) vs. smoothed (red):
![image](https://user-images.githubusercontent.com/12431371/226328949-085a0a70-70ad-42bb-adeb-28e67c279517.png)

**Comment by extremecarver** [comment]
Yeah that looks better for artifacts - but maybe it's an easy region? Is this 10m or 20m interval? With those fake islands maybe some avoidance for interpolation for values <20m could help?

**Comment by agrenott** [comment]
If I remember correctly, this sample comes from 10m step interval.
With the interpolation of source data, I don't think artifacts can appear anymore.

Now the "fake islands" come from the slight oscillations the 3-spline causes on the boundaries. Reducing the spline dimension to 2 or below avoids them, but also degrades the overall smoothing.
